### ISSUE TITLE
AWS EKS configuration question

### ISSUE THREAD

**Issue by john-b-yang** [NovaSky-AI/SkyRL-OpenHands#5]
Hi SkyRL team! I'm working through the tutorial for deploying OpenHands on Kubernetes [here](https://github.com/NovaSky-AI/SkyRL-OpenHands/tree/main/k8s_deploy).

I was able to create an EKS cluster successfully:
```
eksctl create cluster --name openhands-cluster --region us-west-1 --version 1.32 --vpc-private-subnets subnet-1,subnet-2 --without-nodegroup
```

I'm trying to do the step of creating the nodegroup
```
eksctl create nodegroup --config-file nodegroup.yaml
```

nodegroup.yaml Configuration

Configuration:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: openhands-cluster
  # change as needed
  region: us-west-1

nodeGroups:
  - name: nvme-storage-2
    instanceType: i4i.4xlarge
    desiredCapacity: 8
    privateNetworking: false
    volumeSize: 50
    labels:
      node-group: nvme-storage
    securityGroups:
      # Change this to your security group ID
      attachIDs: [sg-...]
    preBootstrapCommands:
      - apt install -y xfsprogs
      # Mount the NVME volume
      - if ! grep -qs '/mnt/nvme' /proc/mounts; then mkfs.xfs -f /dev/nvme1n1; mkdir -p /mnt/nvme; mount /dev/nvme1n1 /mnt/nvme; echo "/dev/nvme1n1 /mnt/nvme xfs defaults 0 0" >> /etc/fstab; fi
```

I'm running into this error:
```
Error: all public subnets from vpc-..., that the cluster was originally created on, have been deleted; to create public nodegroups within vpc-... please manually set valid public subnets via nodeGroup.SubnetIDs
```

The error message is fairly explanatory, but I'm not sure how to go about making the subnets public? I am an AWS newbie, so this is my first time using a lot of these AWS features.

Also, at what point am I supposed to follow these [instructions to run the OpenHands remote runtime](https://github.com/NovaSky-AI/SkyRL-OpenHands/blob/main/openhands/runtime/remote_runtime_server/README.md)? Is it after I've finished up the steps in the k8s deployment tutorial?
